### ISSUE TITLE
Basic Sync Support

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multi-cluster-traffic-controller#43]
**What**

We are adding a sync agent to reflect certain resources defined at the control plane into the data plane. This syncer will also be responsible for reflecting the status of those resources back into the control plane and applying transforms added via the controllers in the control plane. This syncer will lean heavily on what we have learned through use of the KCP sync component

At the end of this work the control plane should no longer talk to the data plane.

**Open Questions**
- how do we choose which namespace on the cluster to sync to? Do we generate a namespace like kcp did based on the tenant namespace?
- Initially we can sync to a known namespace (IE istio-system) 

**Outcome**

We should have basic sync capabilities for gateways and TLS secrets based on access provided by service account secrets. We should capture, patterns, concepts and remaining questions as a Design doc

- [x] Sync DNSRecords based on Ingress #70 
- [x] Remove cluster watch support #70 
- [x] Remove webhook reconcile #70 
- [x] Add capability to sync gateways and secrets
- [x] Add capability to report back the status of a given gateway as a multi-cluster status

**Comment by maleck13** [comment]
I think we need a mechanism for the control plane to say
1) this Gateway is ready to sync
2) this gateway is for your cluster

So the gateway admin will choose a placement label but we then need to reflect the cluster choice on the gateway resource somehow have the sync component see this and then sync down the spec of the gateway

@philbrookes

**Comment by maleck13** [comment]
marking this as done in m2 and moving additonal MVP work to #108
